### PR TITLE
refactor: split source files due to build

### PR DESCRIPTION
**Pull request by pimlie**
feat: add builds for cjs, es and umd
test: add e2e tests for nuxt spa & ssr

### CODE REVIEW

**Comment by galvez** [comment]
Feel free to merge but let's make sure `vue-stator/nuxt` import is still working before releasing a new NPM version ;)

**Comment by pimlie** [comment]
@clarkdo Could you maybe have a look with me at this build issue? For the tests the fixtures are now pointing to `<rootDir>`, which means they use the package.json and thus the dist files. Because Nuxt uses `['main', 'module']` instead of the default `['module', 'main']` the commonjs build file is used but that results in the circleci error for the ssr fixture above. I've debugged this and the problem seems to be that this import here returns an empty object: https://github.com/galvez/vue-stator/blob/feat-tests-refactor/nuxt/plugin.js#L3-L7
The specific error is `Object(...) is not a function on line 27` which is the line of `createStore`

If I edit `node_modules/@nuxt/webpack/dist/webpack.js:5092` and reverse the `mainFields` so Nuxt uses the esm file for vue-stator then the tests do work correctly.

**Comment by pimlie** [comment]
@galvez I think we can merge this pr, we can discuss the mainFields issue with Nuxt separatedly

**Comment by pimlie** [comment]
@galvez ok now its good

**Pull request merged**
